/**:
  ros__parameters:
    'yaw_p_gain': 0.3
    'yaw_i_gain': 0.0
    'yaw_d_gain': 0.1  
    'yaw_threshold': 1.0
            
    'yawrate_p_gain': 300.0
    'yawrate_i_gain': 0.0
    'yawrate_d_gain': 30.0  
            
    'velocity_p_gain': 500.0
    'velocity_i_gain': 10.0
    'velocity_d_gain': 0.0

    'update_rate': 20.0
    'carrot_speed': 1.0
    'move_to_trigger': 2.0
    'catch_up_gain': 0.8
    'catch_up_distance': 1.0
    'look_a_head_distance': 1.0
