/**:
  ros__parameters:
    "loiter_tolerance" : 5.0               
    "heading_tolerance": 15.0
    "loiter_reposition_tolerance": 1.0
    "loiter_move_to_speed": 'standard'

    "yaw_p_gain": 0.3
    "yaw_i_gain": 0.0
    "yaw_d_gain": 0.1  
    "yaw_threshold": 0.1                  
            
    "yawrate_p_gain": 100.0 
    "yawrate_i_gain": 0.0
    "yawrate_d_gain": 30.0 
            
    "velocity_p_gain": 500.0
    "velocity_i_gain": 10.0
    "velocity_d_gain": 0.0